name = "PolyesterWeave"
uuid = "1d0040c9-8b98-4ee7-8388-3f51789ca0ad"
authors = ["Chris Elrod <elrodc@gmail.com> and contributors"]
version = "0.2.2"

[deps]
BitTwiddlingConvenienceFunctions = "62783981-4cbd-42fc-bca8-16325de8dc4b"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
ThreadingUtilities = "8290d209-cae3-49c0-8002-c8c24d57dab5"

[compat]
Aqua = "0.8"
BitTwiddlingConvenienceFunctions = "0.1"
Static = "1"
Test = "<0.1, 1.10"
ThreadingUtilities = "0.5"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
